#+TITLE: Pulsar Rescaling Guideline
#+LATEX_HEADER_EXTRA: \usepackage[left=0.75in, top=1.25in, right=0.75in, bottom=1.25in]{geometry}
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="org.min.css" />
#+OPTIONS: html-postamble:nil
#+OPTIONS: html5-fancy:t
#+OPTIONS: toc:nil
#+OPTIONS: num:2
#+HTML_DOCTYPE: html5

* Rationale

The goal of this document is to formulate a way of rescaling the pulsar
parameters from realistic values to ones more feasible for a global simulation.
The emphasis will be placed on "typical" pulsars that are in the middle of the
radio pulsar population, with $B_{0} \sim 10^{12}\,\mathrm{G}$, and period
$P\sim 1\,\mathrm{s}$. What is special about these pulsars is that, as will be
evident in the following sections, curvature photons typically have macroscopic
free path even near the star. Studying how these pulsars behave will shed light
on how pulsars operate near the death line, and may eventually allow us to put
constraints on pulsar radio mechanisms.

* Basic Scales

For these pulsars, $\gamma_\mathrm{thr}$ no longer makes sense. There is no real
"threshold" for pair production. The free path of curvature photons will scale
with their energies, and even at $\gamma_\mathrm{pc}$, the emitted curvature
photon will not convert in the gap, indicating that voltage will extend beyond
$\gamma_\mathrm{pc}$.

|                                                          | Realistic                                  | Simulation                               |
|----------------------------------------------------------+--------------------------------------------+------------------------------------------|
| Magnetic field                                           | $B\sim 10^{12}\,\mathrm{G}$                | $\tilde{B}\sim 1.6\times 10^5$           |
| Period                                                   | $P\sim 1\,\mathrm{s}$                      | $P\sim 50R_{*}/c$                        |
| $R_{LC}$                                                 | $\sim 5000R_*$                             | $8R_{*}$                                 |
| $\rho_{c}$ at last closed field line                     | $\sim 90R_{*}$                             | $\sim 4R_{*}$                            |
| $\gamma_{0}$                                             | $5.7\times 10^{10}$                        | $\sim 2\times 10^4$                      |
| $\gamma_\mathrm{pc}$                                     | $\sim 1.3\times 10^7$                      | $\sim 2.5\times 10^3$                    |
# | Curvature ph energy $\epsilon_c$ at $\gamma_\mathrm{pc}$ | $\sim 10^3 \sim 10^{-4}\gamma_\mathrm{pc}$ | $\sim 20 \sim 10^{-2}\gamma_\mathrm{pc}$ |

The rest of the scales can become a bit tricky. Curvature photon energy, mean
free path for particles to emit curvature photons, and photon free path all
require some scaling. For example, the dimensionless free path is:

\[
\tilde{\ell}_\mathrm{curv} = \frac{9}{4\alpha}\frac{\rho_c}{R_{*}}\frac{1}{\gamma}
\]

This is the average distance a particle will travel before it emits a curvature
photon. Together with the typical curvature photon energy, it will determine the
curvature energy loss rate for particles in the magnetosphere. For realistic
particles at $\gamma_\mathrm{pc}$, $\tilde{\ell}_\mathrm{curv}\sim 2\times
10^{-3}$. For the simulation parameters the naive formula will give 0.5, which
is much larger than realistic values. Ideally we want to rescale it to $\sim
10^{-2}$. However, this would very likely increase the curvature energy loss
rate by a huge factor, reducing the radiation limited Lorentz factor. Will be
considering this more in the next section.

* Numerical Parameters

At least three dimensionless numerical parameters can be independently tuned:
the characteristic curvature free path $\tilde{\ell}_c$, the normalization for
curvature photon energy $\tilde{\epsilon}_0$, and the normalization for photon
free path $\tilde{\ell}_0$. As a result, the mean free path for curvature
emission will be:

\[
\tilde{\ell}_\mathrm{curv} = \tilde{\ell}_c \frac{\tilde{\rho}_c}{\gamma}
\]

The characteristic energy of curvature photons will be:

\[
\tilde{\epsilon}_c = \epsilon_0 \frac{\gamma^3}{\tilde{\rho}_c}
\]

And the mean free path for the curvature photons to convert to pairs can be
written as:

\[
\tilde{\ell}_\mathrm{ph} \sim \tilde{\ell}_0 \frac{\tilde{\rho}_c}{\epsilon_\mathrm{ph}}\frac{B_Q}{B}
\]

Note that this estimate assumes constant $B$ field and constant radius of
curvature. In reality the free path is ultimately determined by the angle
between photon propagation and the local $B$ field, and the above estimate is
just a crude approximation.

Here is a tentative choice for the 3 numerical parameters:

|                           | Realistic                 | Simulation                    | Reason                                                              |
|---------------------------+---------------------------+-------------------------------+---------------------------------------------------------------------|
| $\tilde{\ell}_\mathrm{c}$ | $\sim 308$                | want $\sim 6$                 | want $\tilde{\ell}_\mathrm{curv} \sim 0.01$ at $\gamma_\mathrm{pc}$ |
| $\tilde{\epsilon}_0$      | $\sim 5.8\times 10^{-17}$ | want $\sim 6.4\times 10^{-9}$ | want $\epsilon_c=25$ at $\gamma_\mathrm{pc}$ and $\rho_c$           |
| $\tilde{\ell}_0$          | $\sim 0.1$                | want $\sim 0.05$              | want similar free paths ($\sim 0.1R_{*}$)                           |

However these shouldn't be freely adjusted, since there are other constraints
that need to be satisfied.

** Lorentz factor when curvature radiation becomes quantum

When $\epsilon_{c} \sim \gamma$, i.e. the curvature photon energy becomes
comparable to the emitting particle, then the curvature radiation formula can't
be used. The spectrum becomes truncated above $\gamma - 1$. In reality, when
$\gamma \sim \gamma_0$, $\epsilon_c \sim 10^{12}$ which is way above $\gamma_0$.
Quantum transition happens around $\gamma \sim 1.2\times 10^9$ which is about
$0.02\gamma_0$.

If we adopt the simulation parameters in the above table, then quantum
transition happens at around $\gamma\sim 2.5\times 10^4$, which is slightly
above $\gamma_0$. This may be a problem, but not a severe one if the particles
can't reach this energy anyway.

** Radiation reaction limit and energy loss rate

To compute the radiation reaction limit, one equates the energy loss rate to
curvature radiation with the acceleration rate:

\[
\frac{\tilde{\epsilon}_c}{\tilde{\ell}_\mathrm{cur}} = \tilde{E}
\]

Plugging in the expressions from above, one can find that:

\[
\gamma_\mathrm{rad} = \left( \frac{\tilde{\ell}_c\tilde{\rho}^2_c}{\tilde{\epsilon}_0}\tilde{E} \right)^{1/4}
\]

This gives $\gamma_\mathrm{rad} \sim 2\times 10^3$ for the numerical parameters
given above. It is comparable to $\gamma_\mathrm{pc}$, which may pose a problem,
since in reality this number is close to 60 times $\gamma_\mathrm{pc}$, right
between $\gamma_\mathrm{pc}$ and $\gamma_0$.
